### ISSUE TITLE
Goblin 0.7.1 fails to parse our PE files

### ISSUE THREAD

**Issue by blitz** [nix-community/lanzaboote#237]
When upgrading to goblin 0.7.1, the UEFI stub dies, because it fails to parse its own PE file:

```
vm-test-run-lanzaboote-systemd-boot-loader-config> machine # [ WARN]: linux-bootloader/src/pe_section.rs@028: Parsing PE failed Malformed entity: Unable to extract certificate. Probably cert_size:1599360838 is malformed!
vm-test-run-lanzaboote-systemd-boot-loader-config> machine # [PANIC]: panicked at 'Failed to extract configuration from binary. Did you run lzbt?: Error { status: INVALID_PARAMETER, data: () }', stub/src/thin.rs:121:10
```

Looks like it's introduced with: https://github.com/m4b/goblin/pull/354

Blocks #196.

/cc @RaitoBezarius

**Comment by RaitoBezarius** [comment]
It's fixed on master, we just need a goblin release.

Le dim. 15 oct. 2023, 14:38, Julian Stecklina ***@***.***> a
écrit :

**Comment by nikstur** [comment]
Seems to still fail with 0.8.2:

```
panicked at stub/src/thin.rs:96:10:\r\nFailed to extract configuration from binary. Did you run lzbt?: Error '
Failed to extract configuration from binary. Did you run lzbt?: Error { status: INVALID_PARAMETER, data: () }
```
